spring.application.name=springCat

spring.datasource.url=jdbc:postgresql://localhost:5432/catRpg
spring.datasource.username=postgres
spring.datasource.password=1405190109
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

