spring.application.name=springCat

# Убираем дефолтные значения после двоеточия, чтобы Render точно подставил свои
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Это поможет избежать падения, если база долго отвечает
spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Принудительно задаем порт внутри конфига
server.port=${PORT:8080}