spring.application.name=springCat

# Основные настройки подключения
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Помогаем Hibernate не падать при старте
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Настройки порта для Render
server.port=${PORT:8080}

# Важно: отключаем проверку метаданных до полной инициализации
spring.datasource.hikari.initialization-fail-timeout=0